---
title: "Test access to BoM data"
author:
  name: "J-M Perraud"
  affiliation: CSIRO.
  email: per202@csiro.au
  url: https://github.com/jmp75/
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: true
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library("sos4R")
```

## NIWA

Two SOS by New Zealands [National Institute of Water and Atmospheric Research](https://www.niwa.co.nz/about/our-company) (NIWA) for hydrometric and climate data, see https://teamwork.niwa.co.nz/display/NEDA/Access+to+Sensor+Data.

```{r niwa_hydro}
niwaHydro <- SOS(url = "https://hydro-sos.niwa.co.nz/",
                  binding = "POX", useDCPs = FALSE,
                  #binding = "KVP",
                  version = "2.0.0",
                 verboseOutput = TRUE)
sosContents(niwaHydro)
```

```{r niwa_hydro_data}
#sosResponseFormats(niwaHydro)
discharge29808 <- getObservation(sos = niwaHydro,
                                 observedProperty = list("Discharge"), # phenomena
                                 featureOfInterest = list("29808"), # sites
                                 #saveOriginal = "../tests/responses/hydro-sos.niwa.co.nz_Discharge_29808.xml",
                                 #responseFormat = "http://www.opengis.net/waterml/2.0",
                                 #inspect = TRUE,
                                 retrieveFOI = FALSE)
sosResult(discharge29808)
```

```{r niwa_climate}
# service offline - HTTP 503
#niwaClimate <- SOS(url = "http://clidb-sos.niwa.co.nz/sos/kvp", binding = "KVP", useDCPs = FALSE, version = "2.0.0")
#sosContents(niwaClimate)
```


## BoM Australia

```{r bom_hydro}
bomHydro <- SOS(url = "http://www.bom.gov.au/waterdata/services?service=SOS&version=2.0.0",
#bomHydro <- SOS(url = "http://www.bom.gov.au/waterdata/services", 
                 binding = "POX",
                 version = "2.0.0",
                useDCPs = FALSE,
                 verboseOutput = TRUE)
sosContents(bomHydro)
```

```{r bom_hydro_data}
#sosResponseFormats(bomHydro)
discharge29808 <- getObservation(sos = bomHydro,
                                 observedProperty = list("Discharge"), # phenomena
                                 featureOfInterest = list("29808"), # sites
                                 #saveOriginal = "../tests/responses/hydro-sos.bom.co.nz_Discharge_29808.xml",
                                 #responseFormat = "http://www.opengis.net/waterml/2.0",
                                 #inspect = TRUE,
                                 retrieveFOI = FALSE)
sosResult(discharge29808)
```

```{r bom_climate}
```


